name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    #   分 时 日 月 周
    - cron: '*/1 */8 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'GitHubAction')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/analysys-sdk/CheckQianfanUrl.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            ls
            chmod -R 777 *
            cd CheckQianfanUrl
            git config core.filemode false
            bash build.sh
            if [ $# == 0 ]; then
              echo "编译成功。。。。。"
              ls
              mv `ls target/*.jar` ../ts.jar
              echo "拷贝成功。。。。。"
              ls ../
            fi
          fi

      - name: ls
        shell: bash
        continue-on-error: true
        run:  ls

      - name: run java project
        shell: bash
        continue-on-error: true
        run: java -jar  ./ts.jar

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
#          server_address: smtp.163.com
#          server_port: 465
#          server_address: smtp.gmail.com
#          server_port: 465
         server_address: smtp.exmail.qq.com
         server_port: 465
         username: ${{ secrets.MAILUSERNAME }}
         password: ${{ secrets.MAILPASSWORD }}
         subject: "[易观千帆]收数地址状态监控"
         to: ${{ secrets.MAIL_LIST }}
         from: GithubActions
         secure: true
        #  body:  |
        #    Build job ( ${{ github.job }} ) of ${{ github.repository }} completed successfully! 
        #    Commit msg: ${{ github.event.head_commit.message }}
         html_body: file://result.html
         ignore_cert: true
         priority: low
